image: debian:testing-slim

stages:
  - testing

test:
  stage: testing
  script:
    - apt-get update
    - apt-get install -y autoconf automake libtool make
    - autoreconf -i
    - CFLAGS="-O3" ./configure --disable-dependency-tracking
    - make distcheck
